### ISSUE TITLE
Application updater

### ISSUE THREAD

**Issue by dunestorm333** [dunestorm333/gbm#2]
GBM will check for updates upon starting and notify you when there is a new version available. The updater will automatically download the update and verify the download's integrity before starting the installation process. **This requires that the installer supports silent installation.**

For Linux, this feature will only be able to re-direct the user to a web-page due to the nature of the OS.

**Comment by MikeMaximus** [comment]
The installers will take the /S flag (case-sensitive) and execute silently.

I did have an updater written a year or two ago that I never pushed.  I over-complicated it, ended up with a bunch of technical problems and ended up rolling the entire thing back.  Then it kinda feel off my radar.

**Comment by dunestorm333** [comment]
> The installers will take the /S flag (case-sensitive) and execute silently.
> 
> I did have an updater written a year or two ago that I never pushed. I over-complicated it, ended up with a bunch of technical problems and ended up rolling the entire thing back. Then it kinda feel off my radar.

Thanks, in that case I'll take a look and see how easy it'd be to overwrite an old version with a new version. In the worst case scenario I can always convert the installer to an MSI :)

I'll also need to look into whether the installer supports closing the open program when doing an upgrade/uninstall. Otherwise I'll have to get the GBM update module to gracefully shutdown itself.
